name: rhythm_reels
description: "rhythm_reels is a small application that automatically cuts a randomly selected videos to a specified beat."
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_audio_waveforms: ^1.2.1+8 # waveform display
  audioplayers: ^6.0.0 # audioplayer for the audio analysis
  awesome_snackbar_content: ^0.1.3 # this really is just for a nice snackbar
  wav: ^1.3.0 # wav file parsing
  path: ^1.8.3
  http: ^1.2.1
  future_debounce_button: ^0.3.0
  pro_image_editor: ^2.5.8
  uuid: ^4.3.3
  path_provider: ^2.1.2 # provides platform specific paths
  updat: ^1.3.2 # auto updating from GitHub
  build_version: ^2.1.1 # useful for auto update workflow
  package_info_plus: ^6.0.0
  dio: ^5.4.2
  archive: ^3.3.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  build_runner: ^2.4.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AppleColorEmoji
      fonts:
         - asset: fonts/AppleColorEmoji.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: fonts/NotoColorEmoji.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
